POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhdmVQYXNzd29yZCIsImlkIjoiNjMxMjM1NmNmNjY4ZjVjNjhjYmI2ODA1IiwiaWF0IjoxNjYyNjUwODk0fQ._EdkMcE0aQ37Tn-S3WnUA8d3XXln4Ta_J4B8IPZcdv8

{
    "title": "Manual With User Joe Blow",
    "author": "Anne Author",
    "url": "https://manualwithuser.com",
    "likes": 0,
    "user": "631222e939d468119738643d"
}