POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvRGVsZXRlNFRva2VuVGVzdCIsImlkIjoiNjMxYjVlNWVjMzRlZDJlYTU2OWJjYzY4IiwiaWF0IjoxNjYyNzM4MDYyLCJleHAiOjE2NjI3NDE2NjJ9.xXt488br8F6rFBtc6xy9TnaU6TRxOY1N1h2WP2OWkBg

{
    "title": "Manual With User Token Test",
    "author": "Anne Author",
    "url": "https://manualwithuser.com",
    "likes": 0,
    "user": "631222e939d468119738643d"
}